# Generated by Django 5.1.7 on 2025-03-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filme', models.CharField(max_length=50)),
                ('ano_lancamento', models.DateField()),
                ('estudio', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('sinopse', models.CharField(max_length=500)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_genero', models.CharField(max_length=20)),
                ('data_cadastro', models.DateField()),
            ],
        ),
    ]
