# Generated by Django 5.1.7 on 2025-03-28 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_filme_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='ano_lancamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='filme',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genero',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
