# Generated by Django 5.1.7 on 2025-03-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_filme_ano_lancamento_alter_filme_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='nome_filme',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='nome_genero',
            new_name='nome',
        ),
    ]
